version: '3.8'

services:
  # Backend API service
  api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_SERVER=db
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=YourStrongPassword123
      - DB_NAME=fitness_tracker
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=1d
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX=100
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # SQL Server database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql

  # Frontend Angular application
  frontend:
    image: node:20-alpine
    ports:
      - "4200:4200"
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm start

volumes:
  sqlserver_data:
