version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fitness_tracker_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fitness_tracker
      MYSQL_USER: fitness_user
      MYSQL_PASSWORD: fitness_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - fitness-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fitness_tracker_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - fitness-network

volumes:
  mysql_data:

networks:
  fitness-network:
    driver: bridge
